download_images:
	curl https://img.icons8.com/cute-clipart/2x/login-rounded-right.png > login-rounded-right.png
	curl https://img.icons8.com/ultraviolet/2x/add-user-male.png > add-user-male.png
	curl https://img.icons8.com/ultraviolet/2x/home-page.png > home-page.png
	curl https://img.icons8.com/flat-round/2x/plus.png > plus.png
	curl https://img.icons8.com/ultraviolet/2x/stack-of-tweets.png > stack-of-tweets.png
	curl https://img.icons8.com/ultraviolet/2x/select-users.png > select-users.png
	curl https://img.icons8.com/fluent/2x/list.png > list.png
	curl https://img.icons8.com/cotton/2x/network-2-1.png > network-2-1.png
	curl https://img.icons8.com/cotton/2x/company.png > company.png
	curl https://img.icons8.com/cotton/2x/settings.png > settings.png
	curl https://img.icons8.com/officel/2x/shutdown.png > shutdown.png
	curl https://img.icons8.com/officel/2x/change-user-male.png > change-user-male.png